"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { creatorChannelId, intelligenceApi } from "./intelligence-api";
export const intelligenceKeys = { all: ["intelligence"] as const, dashboard: () => ["intelligence", "dashboard", creatorChannelId()] as const, trends: () => ["intelligence", "trends", creatorChannelId()] as const, history: () => ["intelligence", "content-history", creatorChannelId()] as const, profile: () => ["intelligence", "profile", creatorChannelId()] as const, sponsorships: () => ["intelligence", "sponsorships"] as const, drafts: () => ["intelligence", "drafts"] as const, feedbackHistory: () => ["intelligence", "feedback-history", creatorChannelId()] as const, feedbackSummary: (days: number) => ["intelligence", "feedback-summary", creatorChannelId(), days] as const, weights: () => ["intelligence", "weights", creatorChannelId()] as const };
export function useDashboard() { return useQuery({ queryKey: intelligenceKeys.dashboard(), queryFn: () => intelligenceApi.dashboard(), enabled: Boolean(creatorChannelId()) }); }
export function useTrends() { return useQuery({ queryKey: intelligenceKeys.trends(), queryFn: () => intelligenceApi.trends(), enabled: Boolean(creatorChannelId()) }); }
export function useContentHistory() { return useQuery({ queryKey: intelligenceKeys.history(), queryFn: () => intelligenceApi.history(), enabled: Boolean(creatorChannelId()) }); }
export function useCreatorProfile() { return useQuery({ queryKey: intelligenceKeys.profile(), queryFn: () => intelligenceApi.profile(), enabled: Boolean(creatorChannelId()) }); }
export function useSponsorships() { return useQuery({ queryKey: intelligenceKeys.sponsorships(), queryFn: () => intelligenceApi.sponsorships(), enabled: Boolean(creatorChannelId()) }); }
export function useEmailDrafts() { return useQuery({ queryKey: intelligenceKeys.drafts(), queryFn: () => intelligenceApi.drafts(), enabled: Boolean(creatorChannelId()) }); }
export function useFeedbackHistory() { return useQuery({ queryKey: intelligenceKeys.feedbackHistory(), queryFn: () => intelligenceApi.feedbackHistory(), enabled: Boolean(creatorChannelId()) }); }
export function useFeedbackSummary(days: number) { return useQuery({ queryKey: intelligenceKeys.feedbackSummary(days), queryFn: () => intelligenceApi.feedbackSummary(days), enabled: Boolean(creatorChannelId()) }); }
export function useFeedbackWeights() { return useQuery({ queryKey: intelligenceKeys.weights(), queryFn: () => intelligenceApi.weights(), enabled: Boolean(creatorChannelId()) }); }
export function useFeedback() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, action, notes }: { id: string; action: "accept" | "reject" | "ignore"; notes?: string }) => intelligenceApi.feedback(id, action, notes), onSuccess: () => qc.invalidateQueries({ queryKey: intelligenceKeys.all }) }); }
export function useGenerate() { const qc = useQueryClient(); return useMutation({ mutationFn: (id: string) => intelligenceApi.generate(id), onSuccess: () => qc.invalidateQueries({ queryKey: intelligenceKeys.history() }) }); }
export function useRegenerate() { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, field }: { id: string; field: string }) => intelligenceApi.regenerate(id, field), onSuccess: () => qc.invalidateQueries({ queryKey: intelligenceKeys.history() }) }); }
export function useEmailActions() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ action, id, notes }: { action: "sync" | "scan" | "summarize" | "draft" | "approve" | "reject"; id?: string; notes?: string }) => { if (action === "sync") return intelligenceApi.syncGmail(); if (action === "scan") return intelligenceApi.scanSponsorships(); if (action === "summarize" && id) return intelligenceApi.summarizeEmail(id); if (action === "draft" && id) return intelligenceApi.draftReply(id, notes); if (action === "approve" && id) return intelligenceApi.approveDraft(id); if (action === "reject" && id) return intelligenceApi.rejectDraft(id, notes); throw new Error("An email action is missing its required id."); }, onSuccess: () => { qc.invalidateQueries({ queryKey: intelligenceKeys.sponsorships() }); qc.invalidateQueries({ queryKey: intelligenceKeys.drafts() }); qc.invalidateQueries({ queryKey: intelligenceKeys.dashboard() }); } }); }
export function useBuildProfile() { const qc = useQueryClient(); return useMutation({ mutationFn: (maxVideos: number) => intelligenceApi.buildProfile(maxVideos), onSuccess: () => qc.invalidateQueries({ queryKey: intelligenceKeys.profile() }) }); }
export function useUpdateWeights() { const qc = useQueryClient(); return useMutation({ mutationFn: () => intelligenceApi.updateWeights(), onSuccess: () => { qc.invalidateQueries({ queryKey: intelligenceKeys.weights() }); qc.invalidateQueries({ queryKey: intelligenceKeys.feedbackSummary(30) }); } }); }
